-- Criação de perfis de usuário estendidos
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text not null check (role in ('admin', 'vendas', 'financeiro')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar função para atualizar updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Trigger para profiles
create trigger handle_profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

-- Tabela de permissões por módulo
create table public.module_permissions (
  id bigint generated by default as identity not null primary key,
  role text not null check (role in ('admin', 'vendas', 'financeiro')),
  module text not null check (module in ('dashboard', 'vendas', 'produtos', 'ordens-servico', 'clientes', 'financeiro', 'relatorios', 'fiscal', 'delivery', 'configuracoes')),
  can_read boolean not null default true,
  can_write boolean not null default false,
  can_delete boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(role, module)
);

-- Inserir permissões padrão
insert into public.module_permissions (role, module, can_read, can_write, can_delete) values
-- Admin tem acesso completo a tudo
('admin', 'dashboard', true, true, true),
('admin', 'vendas', true, true, true),
('admin', 'produtos', true, true, true),
('admin', 'ordens-servico', true, true, true),
('admin', 'clientes', true, true, true),
('admin', 'financeiro', true, true, true),
('admin', 'relatorios', true, true, true),
('admin', 'fiscal', true, true, true),
('admin', 'delivery', true, true, true),
('admin', 'configuracoes', true, true, true),
-- Vendas tem acesso limitado
('vendas', 'dashboard', true, false, false),
('vendas', 'vendas', true, true, false),
('vendas', 'produtos', true, false, false),
('vendas', 'ordens-servico', true, true, false),
('vendas', 'clientes', true, true, false),
('vendas', 'relatorios', true, false, false),
-- Financeiro tem acesso limitado
('financeiro', 'dashboard', true, false, false),
('financeiro', 'financeiro', true, true, false),
('financeiro', 'relatorios', true, true, false),
('financeiro', 'fiscal', true, false, false);

-- RLS (Row Level Security)
alter table public.profiles enable row level security;
alter table public.module_permissions enable row level security;

-- Políticas RLS para profiles
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Admins can view all profiles" on public.profiles for select using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);
create policy "Admins can insert profiles" on public.profiles for insert with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);
create policy "Admins can update all profiles" on public.profiles for update using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);

-- Políticas RLS para module_permissions
create policy "All authenticated users can read module permissions" on public.module_permissions for select using (auth.role() = 'authenticated');
create policy "Admins can manage module permissions" on public.module_permissions for all using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);

-- Trigger para criar profile automaticamente após signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    coalesce(new.raw_user_meta_data->>'role', 'vendas') -- default role
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
