-- Tabela de Clientes
create table public.clients (
  id bigint generated by default as identity not null primary key,
  name text not null,
  phone text,
  address text,
  cpf_cnpj text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger para atualizar updated_at
create trigger handle_clients_updated_at
  before update on public.clients
  for each row execute procedure public.handle_updated_at();

-- RLS (Row Level Security)
alter table public.clients enable row level security;

-- Políticas RLS para clients
create policy "Authenticated users can view clients" on public.clients for select using (auth.role() = 'authenticated');

create policy "Admins and Vendas can insert clients" on public.clients for insert with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')
  )
);

create policy "Admins and Vendas can update clients" on public.clients for update using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')
  )
);

create policy "Admins can delete clients" on public.clients for delete using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);
