-- Enum para formas de pagamento
DO $$ BEGIN
    CREATE TYPE public.payment_method AS ENUM ('pix', 'cartao_credito', 'cartao_debito', 'dinheiro', 'fiado');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Enum para status da venda
DO $$ BEGIN
    CREATE TYPE public.sale_status AS ENUM ('concluida', 'pendente', 'cancelada');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Tabela de Vendas (Sales)
create table public.sales (
  id bigint generated by default as identity not null primary key,
  client_id bigint references public.clients(id) on delete set null, -- Cliente pode ser nulo
  user_id uuid references auth.users(id) on delete set null, -- Vendedor
  total_amount numeric(10, 2) not null,
  payment_method public.payment_method not null,
  status public.sale_status not null default 'concluida',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Itens da Venda (Sale Items)
create table public.sale_items (
  id bigint generated by default as identity not null primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict, -- Impede deletar produto se ele estiver em uma venda
  quantity integer not null check (quantity > 0),
  price numeric(10, 2) not null -- Preço no momento da venda
);

-- Triggers para atualizar updated_at
create trigger handle_sales_updated_at
  before update on public.sales
  for each row execute procedure public.handle_updated_at();

-- RLS (Row Level Security)
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

-- Políticas RLS para sales
create policy "Usuários autenticados podem ver suas próprias vendas" on public.sales for select using (auth.uid() = user_id);
create policy "Admins podem ver todas as vendas" on public.sales for select using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));
create policy "Vendedores podem criar vendas" on public.sales for insert with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')));

-- Políticas RLS para sale_items
create policy "Usuários podem ver itens de suas próprias vendas" on public.sale_items for select using (
  exists (
    select 1 from public.sales
    where sales.id = sale_items.sale_id and sales.user_id = auth.uid()
  )
);
create policy "Admins podem ver todos os itens de venda" on public.sale_items for select using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));
create policy "Vendedores podem inserir itens de venda" on public.sale_items for insert with check (
  exists (
    select 1 from public.sales
    join public.profiles on sales.user_id = profiles.id
    where sales.id = sale_items.sale_id and profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')
  )
);
