-- Tabela de Produtos
create table public.products (
  id bigint generated by default as identity not null primary key,
  name text not null,
  description text,
  category text,
  brand text,
  code text unique, -- Código de barras
  stock_quantity integer not null default 0,
  minimum_stock_level integer not null default 0,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger para atualizar updated_at
create trigger handle_products_updated_at
  before update on public.products
  for each row execute procedure public.handle_updated_at();

-- RLS (Row Level Security)
alter table public.products enable row level security;

-- Políticas RLS para products
create policy "Authenticated users can view products" on public.products for select using (auth.role() = 'authenticated');

create policy "Admins and Vendas can insert products" on public.products for insert with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')
  )
);

create policy "Admins and Vendas can update products" on public.products for update using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')
  )
);

create policy "Admins can delete products" on public.products for delete using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  )
);
