-- Enum para status da Ordem de Serviço
create type public.os_status as enum ('aberta', 'em_andamento', 'aguardando_peca', 'concluida', 'entregue', 'cancelada');

-- Tabela de Ordens de Serviço (Service Orders)
create table public.service_orders (
  id bigint generated by default as identity not null primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null, -- Técnico responsável
  
  -- Informações do Aparelho
  device_type text not null, -- Ex: Celular, Notebook, Tablet
  device_brand text,         -- Ex: Apple, Samsung
  device_model text,         -- Ex: iPhone 15 Pro
  serial_number text,      -- Número de série ou IMEI
  
  -- Descrição do Problema
  reported_issue text not null, -- Defeito relatado pelo cliente
  technician_notes text,      -- Observações do técnico
  
  -- Acessórios
  accessories_included text, -- Ex: Carregador, Cabo, Capa
  
  -- Checklist de Entrada
  power_on boolean not null default false,
  has_password boolean not null default false,
  password_details text, -- PIN, desenho, etc.
  network_status text, -- Ex: 'Funcionando', 'Sem sinal'
  
  -- Checklist de Saída
  exit_test_ok boolean, 
  
  -- Outros
  status public.os_status not null default 'aberta',
  qr_code_url text, -- URL para o QRCode gerado
  client_email text, -- Para futura integração de e-mail
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger para atualizar updated_at
create trigger handle_service_orders_updated_at
  before update on public.service_orders
  for each row execute procedure public.handle_updated_at();

-- RLS (Row Level Security)
alter table public.service_orders enable row level security;

-- Políticas RLS
create policy "Técnicos e Admins podem ver todas as OS" on public.service_orders for select using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')));
create policy "Técnicos e Admins podem criar OS" on public.service_orders for insert with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')));
create policy "Técnicos e Admins podem atualizar OS" on public.service_orders for update using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('admin', 'vendas')));
create policy "Admins podem deletar OS" on public.service_orders for delete using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'admin'));
