
-- Upgrade Service Orders Table
ALTER TABLE service_orders 
ADD COLUMN IF NOT EXISTS opened_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS technician_id UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS total_services NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_parts NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS additional_fees NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS final_value NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS payment_method TEXT,
ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'partially_paid'));

-- Create Service Order Items Table (Parts & Services)
CREATE TABLE IF NOT EXISTS service_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_order_id BIGINT REFERENCES service_orders(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL CHECK (item_type IN ('service', 'part')),
  product_id BIGINT REFERENCES products(id), -- Nullable if it's a manual service not in catalog
  description TEXT NOT NULL,
  quantity NUMERIC(10,2) DEFAULT 1,
  unit_price NUMERIC(10,2) NOT NULL,
  total_price NUMERIC(10,2) NOT NULL,
  technician_id UUID REFERENCES auth.users(id), -- Specific technician for this item
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create OS Status History
CREATE TABLE IF NOT EXISTS service_order_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_order_id BIGINT REFERENCES service_orders(id) ON DELETE CASCADE,
  previous_status TEXT,
  new_status TEXT NOT NULL,
  changed_by UUID REFERENCES auth.users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_os_items_order ON service_order_items(service_order_id);
CREATE INDEX IF NOT EXISTS idx_os_history_order ON service_order_history(service_order_id);

-- Disable RLS on new tables for now to avoid blocking development (as per previous strategy)
ALTER TABLE service_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_order_history DISABLE ROW LEVEL SECURITY;
