-- Create service_orders table
CREATE TABLE IF NOT EXISTS service_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL, -- Assumes clients table exists and uses bigint id
  device_type TEXT NOT NULL,
  device_brand TEXT,
  device_model TEXT,
  serial_number TEXT,
  reported_issue TEXT NOT NULL,
  technician_notes TEXT,
  accessories_included TEXT,
  power_on BOOLEAN DEFAULT FALSE,
  has_password BOOLEAN DEFAULT FALSE,
  password_details TEXT,
  status TEXT DEFAULT 'aberta' CHECK (status IN ('aberta', 'em_andamento', 'aguardando_peca', 'concluida', 'entregue', 'cancelada')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_service_orders_client ON service_orders(client_id);
CREATE INDEX IF NOT EXISTS idx_service_orders_status ON service_orders(status);

-- Trigger for updated_at
CREATE TRIGGER update_service_orders_updated_at
    BEFORE UPDATE ON service_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE service_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for public" ON service_orders FOR ALL USING (true) WITH CHECK (true);
