-- Create product_variations table
CREATE TABLE IF NOT EXISTS product_variations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  name TEXT NOT NULL, -- Display name like "Camiseta Azul P"
  sku TEXT,
  stock_quantity INTEGER DEFAULT 0,
  price NUMERIC(10,2), -- Optional override price
  cost_price NUMERIC(10,2), -- Optional override cost
  attributes JSONB DEFAULT '{}'::jsonb, -- { "color": "Blue", "size": "P" }
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_product_variations_product_id ON product_variations(product_id);

-- Add simple trigger to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_product_variations_updated_at
    BEFORE UPDATE ON product_variations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
