-- =====================================================
-- INTEGRAÇÃO WHATSAPP
-- Data: 08/12/2025
-- Funcionalidades: Envio automático, templates, logs,
--                  agendamento, estatísticas
-- =====================================================

-- ============ TABELA DE CONFIGURAÇÃO ============

CREATE TABLE IF NOT EXISTS public.whatsapp_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_url TEXT,
  api_key TEXT,
  instance_id TEXT,
  ativo BOOLEAN DEFAULT false,
  envio_automatico BOOLEAN DEFAULT false,
  horario_inicio TIME, -- Ex: 08:00
  horario_fim TIME,    -- Ex: 22:00
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.whatsapp_config IS 'Configurações da integração WhatsApp';

-- ============ TABELA DE MENSAGENS ============

CREATE TABLE IF NOT EXISTS public.whatsapp_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo VARCHAR(50) NOT NULL CHECK (modulo IN ('os', 'vendas', 'delivery', 'financeiro', 'marketing')),
  tipo VARCHAR(100) NOT NULL,
  destinatario_id BIGINT,
  telefone VARCHAR(20) NOT NULL,
  mensagem TEXT NOT NULL,
  enviado BOOLEAN DEFAULT false,
  data_envio TIMESTAMP WITH TIME ZONE,
  erro TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.whatsapp_messages IS 'Log de mensagens WhatsApp enviadas';
COMMENT ON COLUMN public.whatsapp_messages.modulo IS 'Módulo de origem: os, vendas, delivery, financeiro, marketing';
COMMENT ON COLUMN public.whatsapp_messages.tipo IS 'Tipo de mensagem: os_recebida, venda_confirmada, etc';
COMMENT ON COLUMN public.whatsapp_messages.metadata IS 'Dados adicionais: scheduled_for, variables, etc';

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_modulo ON public.whatsapp_messages(modulo);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_enviado ON public.whatsapp_messages(enviado);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_created_at ON public.whatsapp_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_telefone ON public.whatsapp_messages(telefone);

-- ============ VIEWS ============

-- View de estatísticas gerais
CREATE OR REPLACE VIEW vw_whatsapp_stats AS
SELECT 
  COUNT(*) as total_mensagens,
  COUNT(CASE WHEN enviado THEN 1 END) as mensagens_enviadas,
  COUNT(CASE WHEN NOT enviado AND erro IS NULL THEN 1 END) as mensagens_pendentes,
  COUNT(CASE WHEN NOT enviado AND erro IS NOT NULL THEN 1 END) as mensagens_falhas,
  ROUND((COUNT(CASE WHEN enviado THEN 1 END)::DECIMAL / NULLIF(COUNT(*), 0) * 100), 2) as taxa_sucesso
FROM whatsapp_messages;

-- View de estatísticas por módulo
CREATE OR REPLACE VIEW vw_whatsapp_stats_por_modulo AS
SELECT 
  modulo,
  COUNT(*) as total,
  COUNT(CASE WHEN enviado THEN 1 END) as enviadas,
  COUNT(CASE WHEN NOT enviado AND erro IS NULL THEN 1 END) as pendentes,
  COUNT(CASE WHEN NOT enviado AND erro IS NOT NULL THEN 1 END) as falhas,
  ROUND((COUNT(CASE WHEN enviado THEN 1 END)::DECIMAL / NULLIF(COUNT(*), 0) * 100), 2) as taxa_sucesso
FROM whatsapp_messages
GROUP BY modulo
ORDER BY total DESC;

-- View de mensagens recentes
CREATE OR REPLACE VIEW vw_whatsapp_recent AS
SELECT 
  id,
  modulo,
  tipo,
  telefone,
  LEFT(mensagem, 100) as mensagem_preview,
  enviado,
  data_envio,
  erro,
  created_at
FROM whatsapp_messages
ORDER BY created_at DESC
LIMIT 100;

-- View de mensagens agendadas
CREATE OR REPLACE VIEW vw_whatsapp_scheduled AS
SELECT 
  id,
  modulo,
  tipo,
  telefone,
  mensagem,
  metadata->>'scheduled_for' as agendado_para,
  created_at
FROM whatsapp_messages
WHERE 
  enviado = false
  AND metadata->>'scheduled' = 'true'
  AND (metadata->>'scheduled_for')::TIMESTAMP > NOW()
ORDER BY (metadata->>'scheduled_for')::TIMESTAMP ASC;

-- ============ FUNÇÕES ============

-- Função para limpar mensagens antigas
CREATE OR REPLACE FUNCTION fn_clean_old_whatsapp_messages(days_to_keep INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM whatsapp_messages
  WHERE created_at < NOW() - (days_to_keep || ' days')::INTERVAL;
  
  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_clean_old_whatsapp_messages IS 'Remove mensagens WhatsApp antigas (padrão: 90 dias)';

-- Função para obter mensagens pendentes
CREATE OR REPLACE FUNCTION fn_get_pending_whatsapp_messages()
RETURNS TABLE (
  id BIGINT,
  modulo VARCHAR,
  tipo VARCHAR,
  telefone VARCHAR,
  mensagem TEXT,
  metadata JSONB
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    wm.id,
    wm.modulo,
    wm.tipo,
    wm.telefone,
    wm.mensagem,
    wm.metadata
  FROM whatsapp_messages wm
  WHERE 
    wm.enviado = false
    AND wm.erro IS NULL
  ORDER BY wm.created_at ASC;
END;
$$ LANGUAGE plpgsql;

-- Função para processar mensagens agendadas
CREATE OR REPLACE FUNCTION fn_process_scheduled_whatsapp()
RETURNS INTEGER AS $$
DECLARE
  processed_count INTEGER := 0;
  msg RECORD;
BEGIN
  FOR msg IN 
    SELECT * FROM whatsapp_messages
    WHERE 
      enviado = false
      AND metadata->>'scheduled' = 'true'
      AND (metadata->>'scheduled_for')::TIMESTAMP <= NOW()
  LOOP
    -- Marcar como pronta para envio (remover flag de agendada)
    UPDATE whatsapp_messages
    SET metadata = metadata - 'scheduled'
    WHERE id = msg.id;
    
    processed_count := processed_count + 1;
  END LOOP;
  
  RETURN processed_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_process_scheduled_whatsapp IS 'Processa mensagens agendadas que chegaram no horário';

-- ============ TRIGGERS ============

-- Trigger para atualizar updated_at
CREATE OR REPLACE FUNCTION fn_update_whatsapp_config_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_whatsapp_config_timestamp ON public.whatsapp_config;
CREATE TRIGGER trg_update_whatsapp_config_timestamp
  BEFORE UPDATE ON public.whatsapp_config
  FOR EACH ROW
  EXECUTE FUNCTION fn_update_whatsapp_config_timestamp();

-- ============ RLS (Row Level Security) ============

ALTER TABLE public.whatsapp_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;

-- Políticas para config
CREATE POLICY "Usuários autenticados podem ver config" ON public.whatsapp_config FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins podem atualizar config" ON public.whatsapp_config FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins podem inserir config" ON public.whatsapp_config FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Políticas para mensagens
CREATE POLICY "Usuários autenticados podem ver mensagens" ON public.whatsapp_messages FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Usuários autenticados podem criar mensagens" ON public.whatsapp_messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Usuários autenticados podem atualizar mensagens" ON public.whatsapp_messages FOR UPDATE USING (auth.role() = 'authenticated');

-- ============ DADOS INICIAIS ============

-- Inserir configuração padrão
INSERT INTO public.whatsapp_config (ativo, envio_automatico, horario_inicio, horario_fim)
VALUES (false, false, '08:00', '22:00')
ON CONFLICT DO NOTHING;

-- ============ COMENTÁRIOS FINAIS ============

COMMENT ON COLUMN public.whatsapp_messages.telefone IS 'Telefone no formato: 5511999999999';
COMMENT ON COLUMN public.whatsapp_config.horario_inicio IS 'Horário de início para envio automático (ex: 08:00)';
COMMENT ON COLUMN public.whatsapp_config.horario_fim IS 'Horário de fim para envio automático (ex: 22:00)';
