-- Create transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount NUMERIC(10,2) NOT NULL, -- Positive for income, can be handled by type
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  category TEXT, -- e.g., 'Vendas', 'Aluguel', 'Fornecedores'
  status TEXT DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'cancelled')),
  date DATE DEFAULT CURRENT_DATE,
  due_date DATE, -- For accounts payable/receivable
  payment_method TEXT, -- 'pix', 'credit_card', 'cash', etc.
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for date filtering (common in dashboards)
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);

-- Trigger for updated_at
CREATE TRIGGER update_transactions_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
