-- ==========================================
-- CORREÇÕES SUPABASE - SMB MIGRATION
-- ==========================================

-- 1. Desabilitar RLS temporariamente
ALTER TABLE IF EXISTS public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.clients DISABLE ROW LEVEL SECURITY;

-- 2. Adicionar coluna email em clients se não existir
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_schema = 'public' 
                  AND table_name = 'clients' 
                  AND column_name = 'email') THEN
        ALTER TABLE public.clients ADD COLUMN email text;
    END IF;
END $$;

-- 3. Criar tipos ENUM se não existirem
DO $$
BEGIN
    CREATE TYPE public.payment_method AS ENUM ('pix', 'cartao_credito', 'cartao_debito', 'dinheiro', 'fiado');
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'Tipo payment_method já existe';
END $$;

DO $$
BEGIN
    CREATE TYPE public.sale_status AS ENUM ('concluida', 'pendente', 'cancelada');
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE 'Tipo sale_status já existe';
END $$;

-- 4. Criar tabela sales se não existir
CREATE TABLE IF NOT EXISTS public.sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    total_amount numeric(10, 2) NOT NULL,
    payment_method public.payment_method NOT NULL,
    status public.sale_status NOT NULL DEFAULT 'concluida',
    discount numeric(10,2) DEFAULT 0,
    addition numeric(10,2) DEFAULT 0,
    installments integer DEFAULT 1,
    type text DEFAULT 'sale',
    notes text,
    amount_paid numeric(10,2) DEFAULT 0,
    change_amount numeric(10,2) DEFAULT 0,
    client_cpf text,
    client_name text,
    plate text,
    table_number integer,
    command_number integer,
    waiter_id integer,
    delivery_fee numeric(10,2) DEFAULT 0,
    service_fee numeric(10,2) DEFAULT 0,
    service_percentage numeric(5,2) DEFAULT 0,
    nfe_key text,
    nfe_number integer,
    nfe_status text,
    nfe_date timestamp with time zone,
    nfe_time text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Criar tabela sale_items se não existir
CREATE TABLE IF NOT EXISTS public.sale_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    price numeric(10, 2) NOT NULL,
    total_price numeric(10,2),
    discount numeric(10,2) DEFAULT 0,
    addition numeric(10,2) DEFAULT 0,
    unit text DEFAULT 'UN',
    real_cost numeric(10,2),
    profit numeric(10,2),
    commission numeric(10,2),
    icms_rate numeric(5,2) DEFAULT 0,
    ipi_rate numeric(5,2) DEFAULT 0,
    pis_rate numeric(5,2) DEFAULT 0,
    cofins_rate numeric(5,2) DEFAULT 0,
    cfop text,
    cst_icms text,
    cst_ipi text,
    cst_pis text,
    cst_cofins text,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Criar função updated_at se não existir
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Criar triggers updated_at
DO $$
BEGIN
    -- Para sales
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_sales_updated_at') THEN
        CREATE TRIGGER update_sales_updated_at
            BEFORE UPDATE ON public.sales
            FOR EACH ROW
            EXECUTE FUNCTION public.handle_updated_at();
    END IF;
    
    -- Para sale_items
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_sale_items_updated_at') THEN
        CREATE TRIGGER update_sale_items_updated_at
            BEFORE UPDATE ON public.sale_items
            FOR EACH ROW
            EXECUTE FUNCTION public.handle_updated_at();
    END IF;
END $$;

-- 8. Configurar RLS corretamente
DO $$
BEGIN
    -- Habilitar RLS
    ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
    
    -- Criar políticas para products
    DROP POLICY IF EXISTS "Enable read access for all users" ON public.products;
    CREATE POLICY "Enable read access for all users" 
        ON public.products 
        FOR SELECT 
        USING (true);
    
    -- Criar políticas para clients
    DROP POLICY IF EXISTS "Enable read access for all users" ON public.clients;
    CREATE POLICY "Enable read access for all users" 
        ON public.clients 
        FOR SELECT 
        USING (true);
    
    -- Criar políticas para sales
    DROP POLICY IF EXISTS "Users can view their own sales" ON public.sales;
    CREATE POLICY "Users can view their own sales" 
        ON public.sales 
        FOR SELECT 
        USING (auth.uid() = user_id);
    
    DROP POLICY IF EXISTS "Admins can view all sales" ON public.sales;
    CREATE POLICY "Admins can view all sales" 
        ON public.sales 
        FOR SELECT 
        USING (EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        ));
    
    -- Criar políticas para sale_items
    DROP POLICY IF EXISTS "Users can view their sale items" ON public.sale_items;
    CREATE POLICY "Users can view their sale items" 
        ON public.sale_items 
        FOR SELECT 
        USING (EXISTS (
            SELECT 1 FROM public.sales 
            WHERE sales.id = sale_items.sale_id 
            AND sales.user_id = auth.uid()
        ));
    
    DROP POLICY IF EXISTS "Admins can view all sale items" ON public.sale_items;
    CREATE POLICY "Admins can view all sale items" 
        ON public.sale_items 
        FOR SELECT 
        USING (EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        ));
    
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Erro ao configurar RLS: %', SQLERRM;
END $$;

-- 9. Criar índice para melhorar performance
CREATE INDEX IF NOT EXISTS idx_sales_user_id ON public.sales(user_id);
CREATE INDEX IF NOT EXISTS idx_sales_client_id ON public.sales(client_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON public.sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON public.sale_items(product_id);

-- 10. Mensagem de sucesso
DO $$
BEGIN
    RAISE NOTICE '✅ Estrutura corrigida com sucesso!';
    RAISE NOTICE '✅ Tabelas: products, clients, sales, sale_items';
    RAISE NOTICE '✅ RLS configurado';
    RAISE NOTICE '✅ Índices criados';
END $$;
